/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mongoDB.model.Keys;
import mongoDB.model.Transaction;
import mongoDB.model.tables.records.FdaccountRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fdaccount extends TableImpl<FdaccountRecord> {

    private static final long serialVersionUID = -1233726159;

    /**
     * The reference instance of <code>transaction.fdAccount</code>
     */
    public static final Fdaccount FDACCOUNT = new Fdaccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FdaccountRecord> getRecordType() {
        return FdaccountRecord.class;
    }

    /**
     * The column <code>transaction.fdAccount.fdAccountNumber</code>.
     */
    public final TableField<FdaccountRecord, String> FDACCOUNTNUMBER = createField("fdAccountNumber", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>transaction.fdAccount.fdType</code>.
     */
    public final TableField<FdaccountRecord, String> FDTYPE = createField("fdType", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false), this, "");

    /**
     * The column <code>transaction.fdAccount.title</code>.
     */
    public final TableField<FdaccountRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>transaction.fdAccount.description</code>.
     */
    public final TableField<FdaccountRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>transaction.fdAccount.refKey</code>.
     */
    public final TableField<FdaccountRecord, String> REFKEY = createField("refKey", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>transaction.fdAccount.cif</code>.
     */
    public final TableField<FdaccountRecord, String> CIF = createField("cif", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>transaction.fdAccount.currency</code>.
     */
    public final TableField<FdaccountRecord, String> CURRENCY = createField("currency", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

    /**
     * The column <code>transaction.fdAccount.intRate</code>.
     */
    public final TableField<FdaccountRecord, BigDecimal> INTRATE = createField("intRate", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2), this, "");

    /**
     * The column <code>transaction.fdAccount.originalAmount</code>.
     */
    public final TableField<FdaccountRecord, BigDecimal> ORIGINALAMOUNT = createField("originalAmount", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2).nullable(false), this, "");

    /**
     * The column <code>transaction.fdAccount.withDraw</code>.
     */
    public final TableField<FdaccountRecord, BigDecimal> WITHDRAW = createField("withDraw", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2), this, "");

    /**
     * The column <code>transaction.fdAccount.interestAccrued</code>.
     */
    public final TableField<FdaccountRecord, BigDecimal> INTERESTACCRUED = createField("interestAccrued", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2), this, "");

    /**
     * The column <code>transaction.fdAccount.interestPay</code>.
     */
    public final TableField<FdaccountRecord, BigDecimal> INTERESTPAY = createField("interestPay", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2), this, "");

    /**
     * The column <code>transaction.fdAccount.interestPaid</code>.
     */
    public final TableField<FdaccountRecord, BigDecimal> INTERESTPAID = createField("interestPaid", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2), this, "");

    /**
     * The column <code>transaction.fdAccount.fromDate</code>.
     */
    public final TableField<FdaccountRecord, Date> FROMDATE = createField("fromDate", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>transaction.fdAccount.toDate</code>.
     */
    public final TableField<FdaccountRecord, Date> TODATE = createField("toDate", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>transaction.fdAccount.nextGSPayDate</code>.
     */
    public final TableField<FdaccountRecord, Date> NEXTGSPAYDATE = createField("nextGSPayDate", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>transaction.fdAccount.goalSave</code>.
     */
    public final TableField<FdaccountRecord, Byte> GOALSAVE = createField("goalSave", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>transaction.fdAccount.autoAccrue</code>.
     */
    public final TableField<FdaccountRecord, Byte> AUTOACCRUE = createField("autoAccrue", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>transaction.fdAccount.createDate</code>.
     */
    public final TableField<FdaccountRecord, Date> CREATEDATE = createField("createDate", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>transaction.fdAccount.response</code>.
     */
    public final TableField<FdaccountRecord, String> RESPONSE = createField("response", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this, "");

    /**
     * The column <code>transaction.fdAccount.prstatus</code>.
     */
    public final TableField<FdaccountRecord, Integer> PRSTATUS = createField("prstatus", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>transaction.fdAccount.status</code>.
     */
    public final TableField<FdaccountRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>transaction.fdAccount.createdAt</code>.
     */
    public final TableField<FdaccountRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>transaction.fdAccount.modifyAt</code>.
     */
    public final TableField<FdaccountRecord, Timestamp> MODIFYAT = createField("modifyAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>transaction.fdAccount.accountRefNo</code>.
     */
    public final TableField<FdaccountRecord, String> ACCOUNTREFNO = createField("accountRefNo", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>transaction.fdAccount</code> table reference
     */
    public Fdaccount() {
        this("fdAccount", null);
    }

    /**
     * Create an aliased <code>transaction.fdAccount</code> table reference
     */
    public Fdaccount(String alias) {
        this(alias, FDACCOUNT);
    }

    private Fdaccount(String alias, Table<FdaccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private Fdaccount(String alias, Table<FdaccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Transaction.TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FdaccountRecord> getPrimaryKey() {
        return Keys.KEY_FDACCOUNT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FdaccountRecord>> getKeys() {
        return Arrays.<UniqueKey<FdaccountRecord>>asList(Keys.KEY_FDACCOUNT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fdaccount as(String alias) {
        return new Fdaccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fdaccount rename(String name) {
        return new Fdaccount(name, null);
    }
}
