/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mongoDB.model.Keys;
import mongoDB.model.Transaction;
import mongoDB.model.tables.records.FdtypeRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fdtype extends TableImpl<FdtypeRecord> {

    private static final long serialVersionUID = 2009174567;

    /**
     * The reference instance of <code>transaction.fdType</code>
     */
    public static final Fdtype FDTYPE = new Fdtype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FdtypeRecord> getRecordType() {
        return FdtypeRecord.class;
    }

    /**
     * The column <code>transaction.fdType.fdTypeId</code>.
     */
    public final TableField<FdtypeRecord, String> FDTYPEID = createField("fdTypeId", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false), this, "");

    /**
     * The column <code>transaction.fdType.adminCif</code>.
     */
    public final TableField<FdtypeRecord, String> ADMINCIF = createField("adminCif", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>transaction.fdType.typeName</code>.
     */
    public final TableField<FdtypeRecord, String> TYPENAME = createField("typeName", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>transaction.fdType.term</code>.
     */
    public final TableField<FdtypeRecord, Integer> TERM = createField("term", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>transaction.fdType.termCd</code>.
     */
    public final TableField<FdtypeRecord, String> TERMCD = createField("termCd", org.jooq.impl.SQLDataType.CHAR.length(2).defaultValue(org.jooq.impl.DSL.inline("D", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>transaction.fdType.intRate</code>.
     */
    public final TableField<FdtypeRecord, BigDecimal> INTRATE = createField("intRate", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2), this, "");

    /**
     * The column <code>transaction.fdType.intFreq</code>.
     */
    public final TableField<FdtypeRecord, String> INTFREQ = createField("intFreq", org.jooq.impl.SQLDataType.CHAR.length(2).defaultValue(org.jooq.impl.DSL.inline("M", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>transaction.fdType.intCdByTime</code>.
     */
    public final TableField<FdtypeRecord, Integer> INTCDBYTIME = createField("intCdByTime", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>transaction.fdType.overIntCd</code>.
     */
    public final TableField<FdtypeRecord, Integer> OVERINTCD = createField("overIntCd", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>transaction.fdType.preIntCd</code>.
     */
    public final TableField<FdtypeRecord, Integer> PREINTCD = createField("preIntCd", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>transaction.fdType.preAllow</code>.
     */
    public final TableField<FdtypeRecord, Integer> PREALLOW = createField("preAllow", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>transaction.fdType.status</code>.
     */
    public final TableField<FdtypeRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>transaction.fdType.createdAt</code>.
     */
    public final TableField<FdtypeRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>transaction.fdType.modifyAt</code>.
     */
    public final TableField<FdtypeRecord, Timestamp> MODIFYAT = createField("modifyAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>transaction.fdType</code> table reference
     */
    public Fdtype() {
        this("fdType", null);
    }

    /**
     * Create an aliased <code>transaction.fdType</code> table reference
     */
    public Fdtype(String alias) {
        this(alias, FDTYPE);
    }

    private Fdtype(String alias, Table<FdtypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Fdtype(String alias, Table<FdtypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Transaction.TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FdtypeRecord> getPrimaryKey() {
        return Keys.KEY_FDTYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FdtypeRecord>> getKeys() {
        return Arrays.<UniqueKey<FdtypeRecord>>asList(Keys.KEY_FDTYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fdtype as(String alias) {
        return new Fdtype(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fdtype rename(String name) {
        return new Fdtype(name, null);
    }
}
