/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mongoDB.model.Keys;
import mongoDB.model.Transaction;
import mongoDB.model.tables.records.ScheduleconfigRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scheduleconfig extends TableImpl<ScheduleconfigRecord> {

    private static final long serialVersionUID = 633736715;

    /**
     * The reference instance of <code>transaction.scheduleConfig</code>
     */
    public static final Scheduleconfig SCHEDULECONFIG = new Scheduleconfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScheduleconfigRecord> getRecordType() {
        return ScheduleconfigRecord.class;
    }

    /**
     * The column <code>transaction.scheduleConfig.cif</code>.
     */
    public final TableField<ScheduleconfigRecord, String> CIF = createField("cif", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>transaction.scheduleConfig.feeId</code>.
     */
    public final TableField<ScheduleconfigRecord, Integer> FEEID = createField("feeId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>transaction.scheduleConfig.beginDate</code>.
     */
    public final TableField<ScheduleconfigRecord, Long> BEGINDATE = createField("beginDate", org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>transaction.scheduleConfig.autoRepeat</code>.
     */
    public final TableField<ScheduleconfigRecord, Integer> AUTOREPEAT = createField("autoRepeat", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>transaction.scheduleConfig.status</code>.
     */
    public final TableField<ScheduleconfigRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>transaction.scheduleConfig.createdAt</code>.
     */
    public final TableField<ScheduleconfigRecord, Long> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>transaction.scheduleConfig.modifiedAt</code>.
     */
    public final TableField<ScheduleconfigRecord, Long> MODIFIEDAT = createField("modifiedAt", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>transaction.scheduleConfig</code> table reference
     */
    public Scheduleconfig() {
        this("scheduleConfig", null);
    }

    /**
     * Create an aliased <code>transaction.scheduleConfig</code> table reference
     */
    public Scheduleconfig(String alias) {
        this(alias, SCHEDULECONFIG);
    }

    private Scheduleconfig(String alias, Table<ScheduleconfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private Scheduleconfig(String alias, Table<ScheduleconfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Transaction.TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScheduleconfigRecord> getPrimaryKey() {
        return Keys.KEY_SCHEDULECONFIG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScheduleconfigRecord>> getKeys() {
        return Arrays.<UniqueKey<ScheduleconfigRecord>>asList(Keys.KEY_SCHEDULECONFIG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Scheduleconfig as(String alias) {
        return new Scheduleconfig(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Scheduleconfig rename(String name) {
        return new Scheduleconfig(name, null);
    }
}
