/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import mongoDB.model.tables.Fdaccount;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdaccountRecord extends UpdatableRecordImpl<FdaccountRecord> {

    private static final long serialVersionUID = -50100315;

    /**
     * Setter for <code>transaction.fdAccount.fdAccountNumber</code>.
     */
    public void setFdaccountnumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.fdAccountNumber</code>.
     */
    public String getFdaccountnumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transaction.fdAccount.fdType</code>.
     */
    public void setFdtype(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.fdType</code>.
     */
    public String getFdtype() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.fdAccount.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.fdAccount.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transaction.fdAccount.refKey</code>.
     */
    public void setRefkey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.refKey</code>.
     */
    public String getRefkey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>transaction.fdAccount.cif</code>.
     */
    public void setCif(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.cif</code>.
     */
    public String getCif() {
        return (String) get(5);
    }

    /**
     * Setter for <code>transaction.fdAccount.currency</code>.
     */
    public void setCurrency(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.currency</code>.
     */
    public String getCurrency() {
        return (String) get(6);
    }

    /**
     * Setter for <code>transaction.fdAccount.intRate</code>.
     */
    public void setIntrate(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.intRate</code>.
     */
    public BigDecimal getIntrate() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>transaction.fdAccount.originalAmount</code>.
     */
    public void setOriginalamount(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.originalAmount</code>.
     */
    public BigDecimal getOriginalamount() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>transaction.fdAccount.withDraw</code>.
     */
    public void setWithdraw(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.withDraw</code>.
     */
    public BigDecimal getWithdraw() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>transaction.fdAccount.interestAccrued</code>.
     */
    public void setInterestaccrued(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.interestAccrued</code>.
     */
    public BigDecimal getInterestaccrued() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>transaction.fdAccount.interestPay</code>.
     */
    public void setInterestpay(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.interestPay</code>.
     */
    public BigDecimal getInterestpay() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>transaction.fdAccount.interestPaid</code>.
     */
    public void setInterestpaid(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.interestPaid</code>.
     */
    public BigDecimal getInterestpaid() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>transaction.fdAccount.fromDate</code>.
     */
    public void setFromdate(Date value) {
        set(13, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.fromDate</code>.
     */
    public Date getFromdate() {
        return (Date) get(13);
    }

    /**
     * Setter for <code>transaction.fdAccount.toDate</code>.
     */
    public void setTodate(Date value) {
        set(14, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.toDate</code>.
     */
    public Date getTodate() {
        return (Date) get(14);
    }

    /**
     * Setter for <code>transaction.fdAccount.nextGSPayDate</code>.
     */
    public void setNextgspaydate(Date value) {
        set(15, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.nextGSPayDate</code>.
     */
    public Date getNextgspaydate() {
        return (Date) get(15);
    }

    /**
     * Setter for <code>transaction.fdAccount.goalSave</code>.
     */
    public void setGoalsave(Byte value) {
        set(16, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.goalSave</code>.
     */
    public Byte getGoalsave() {
        return (Byte) get(16);
    }

    /**
     * Setter for <code>transaction.fdAccount.autoAccrue</code>.
     */
    public void setAutoaccrue(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.autoAccrue</code>.
     */
    public Byte getAutoaccrue() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>transaction.fdAccount.createDate</code>.
     */
    public void setCreatedate(Date value) {
        set(18, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.createDate</code>.
     */
    public Date getCreatedate() {
        return (Date) get(18);
    }

    /**
     * Setter for <code>transaction.fdAccount.response</code>.
     */
    public void setResponse(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.response</code>.
     */
    public String getResponse() {
        return (String) get(19);
    }

    /**
     * Setter for <code>transaction.fdAccount.prstatus</code>.
     */
    public void setPrstatus(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.prstatus</code>.
     */
    public Integer getPrstatus() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>transaction.fdAccount.status</code>.
     */
    public void setStatus(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>transaction.fdAccount.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(22, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(22);
    }

    /**
     * Setter for <code>transaction.fdAccount.modifyAt</code>.
     */
    public void setModifyat(Timestamp value) {
        set(23, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.modifyAt</code>.
     */
    public Timestamp getModifyat() {
        return (Timestamp) get(23);
    }

    /**
     * Setter for <code>transaction.fdAccount.accountRefNo</code>.
     */
    public void setAccountrefno(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>transaction.fdAccount.accountRefNo</code>.
     */
    public String getAccountrefno() {
        return (String) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FdaccountRecord
     */
    public FdaccountRecord() {
        super(Fdaccount.FDACCOUNT);
    }

    /**
     * Create a detached, initialised FdaccountRecord
     */
    public FdaccountRecord(String fdaccountnumber, String fdtype, String title, String description, String refkey, String cif, String currency, BigDecimal intrate, BigDecimal originalamount, BigDecimal withdraw, BigDecimal interestaccrued, BigDecimal interestpay, BigDecimal interestpaid, Date fromdate, Date todate, Date nextgspaydate, Byte goalsave, Byte autoaccrue, Date createdate, String response, Integer prstatus, Integer status, Timestamp createdat, Timestamp modifyat, String accountrefno) {
        super(Fdaccount.FDACCOUNT);

        set(0, fdaccountnumber);
        set(1, fdtype);
        set(2, title);
        set(3, description);
        set(4, refkey);
        set(5, cif);
        set(6, currency);
        set(7, intrate);
        set(8, originalamount);
        set(9, withdraw);
        set(10, interestaccrued);
        set(11, interestpay);
        set(12, interestpaid);
        set(13, fromdate);
        set(14, todate);
        set(15, nextgspaydate);
        set(16, goalsave);
        set(17, autoaccrue);
        set(18, createdate);
        set(19, response);
        set(20, prstatus);
        set(21, status);
        set(22, createdat);
        set(23, modifyat);
        set(24, accountrefno);
    }
}
