/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import javax.annotation.Generated;

import mongoDB.model.tables.Paymentschedule;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentscheduleRecord extends UpdatableRecordImpl<PaymentscheduleRecord> {

    private static final long serialVersionUID = -1064098604;

    /**
     * Setter for <code>transaction.paymentSchedule.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.cif</code>.
     */
    public void setCif(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.cif</code>.
     */
    public String getCif() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.refKey</code>.
     */
    public void setRefkey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.refKey</code>.
     */
    public String getRefkey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.displayScheduleId</code>.
     */
    public void setDisplayscheduleid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.displayScheduleId</code>.
     */
    public String getDisplayscheduleid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.creditAccount</code>.
     */
    public void setCreditaccount(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.creditAccount</code>.
     */
    public String getCreditaccount() {
        return (String) get(4);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.cardNumber</code>.
     */
    public void setCardnumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.cardNumber</code>.
     */
    public String getCardnumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.creditName</code>.
     */
    public void setCreditname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.creditName</code>.
     */
    public String getCreditname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.transactionAmount</code>.
     */
    public void setTransactionamount(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.transactionAmount</code>.
     */
    public String getTransactionamount() {
        return (String) get(7);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.transactionCurrency</code>.
     */
    public void setTransactioncurrency(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.transactionCurrency</code>.
     */
    public String getTransactioncurrency() {
        return (String) get(8);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.transactionDetail</code>.
     */
    public void setTransactiondetail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.transactionDetail</code>.
     */
    public String getTransactiondetail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.chargeAccount</code>.
     */
    public void setChargeaccount(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.chargeAccount</code>.
     */
    public String getChargeaccount() {
        return (String) get(10);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.cityCode</code>.
     */
    public void setCitycode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.cityCode</code>.
     */
    public String getCitycode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.bankCode</code>.
     */
    public void setBankcode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.bankCode</code>.
     */
    public String getBankcode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.branchCode</code>.
     */
    public void setBranchcode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.branchCode</code>.
     */
    public String getBranchcode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.typeDescription</code>.
     */
    public void setTypedescription(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.typeDescription</code>.
     */
    public Integer getTypedescription() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.feeId</code>.
     */
    public void setFeeid(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.feeId</code>.
     */
    public Integer getFeeid() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.beginDate</code>.
     */
    public void setBegindate(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.beginDate</code>.
     */
    public Long getBegindate() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.nextDate</code>.
     */
    public void setNextdate(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.nextDate</code>.
     */
    public Long getNextdate() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.autoRepeat</code>.
     */
    public void setAutorepeat(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.autoRepeat</code>.
     */
    public Integer getAutorepeat() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.status</code>.
     */
    public void setStatus(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.createdDate</code>.
     */
    public void setCreateddate(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.createdDate</code>.
     */
    public Long getCreateddate() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.createdAt</code>.
     */
    public void setCreatedat(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.createdAt</code>.
     */
    public Long getCreatedat() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>transaction.paymentSchedule.modifiedAt</code>.
     */
    public void setModifiedat(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>transaction.paymentSchedule.modifiedAt</code>.
     */
    public Long getModifiedat() {
        return (Long) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentscheduleRecord
     */
    public PaymentscheduleRecord() {
        super(Paymentschedule.PAYMENTSCHEDULE);
    }

    /**
     * Create a detached, initialised PaymentscheduleRecord
     */
    public PaymentscheduleRecord(Integer id, String cif, String refkey, String displayscheduleid, String creditaccount, String cardnumber, String creditname, String transactionamount, String transactioncurrency, String transactiondetail, String chargeaccount, String citycode, String bankcode, String branchcode, Integer typedescription, Integer feeid, Long begindate, Long nextdate, Integer autorepeat, Integer status, Long createddate, Long createdat, Long modifiedat) {
        super(Paymentschedule.PAYMENTSCHEDULE);

        set(0, id);
        set(1, cif);
        set(2, refkey);
        set(3, displayscheduleid);
        set(4, creditaccount);
        set(5, cardnumber);
        set(6, creditname);
        set(7, transactionamount);
        set(8, transactioncurrency);
        set(9, transactiondetail);
        set(10, chargeaccount);
        set(11, citycode);
        set(12, bankcode);
        set(13, branchcode);
        set(14, typedescription);
        set(15, feeid);
        set(16, begindate);
        set(17, nextdate);
        set(18, autorepeat);
        set(19, status);
        set(20, createddate);
        set(21, createdat);
        set(22, modifiedat);
    }
}
