/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import javax.annotation.Generated;

import mongoDB.model.tables.Scheduleconfig;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleconfigRecord extends UpdatableRecordImpl<ScheduleconfigRecord> implements Record7<String, Integer, Long, Integer, Integer, Long, Long> {

    private static final long serialVersionUID = 1892268497;

    /**
     * Setter for <code>transaction.scheduleConfig.cif</code>.
     */
    public void setCif(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.scheduleConfig.cif</code>.
     */
    public String getCif() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transaction.scheduleConfig.feeId</code>.
     */
    public void setFeeid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.scheduleConfig.feeId</code>.
     */
    public Integer getFeeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>transaction.scheduleConfig.beginDate</code>.
     */
    public void setBegindate(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.scheduleConfig.beginDate</code>.
     */
    public Long getBegindate() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>transaction.scheduleConfig.autoRepeat</code>.
     */
    public void setAutorepeat(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.scheduleConfig.autoRepeat</code>.
     */
    public Integer getAutorepeat() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>transaction.scheduleConfig.status</code>.
     */
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.scheduleConfig.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>transaction.scheduleConfig.createdAt</code>.
     */
    public void setCreatedat(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.scheduleConfig.createdAt</code>.
     */
    public Long getCreatedat() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>transaction.scheduleConfig.modifiedAt</code>.
     */
    public void setModifiedat(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.scheduleConfig.modifiedAt</code>.
     */
    public Long getModifiedat() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Integer, Long, Integer, Integer, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Integer, Long, Integer, Integer, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Scheduleconfig.SCHEDULECONFIG.CIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Scheduleconfig.SCHEDULECONFIG.FEEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Scheduleconfig.SCHEDULECONFIG.BEGINDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Scheduleconfig.SCHEDULECONFIG.AUTOREPEAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Scheduleconfig.SCHEDULECONFIG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Scheduleconfig.SCHEDULECONFIG.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Scheduleconfig.SCHEDULECONFIG.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFeeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getBegindate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAutorepeat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord value1(String value) {
        setCif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord value2(Integer value) {
        setFeeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord value3(Long value) {
        setBegindate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord value4(Integer value) {
        setAutorepeat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord value6(Long value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord value7(Long value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleconfigRecord values(String value1, Integer value2, Long value3, Integer value4, Integer value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduleconfigRecord
     */
    public ScheduleconfigRecord() {
        super(Scheduleconfig.SCHEDULECONFIG);
    }

    /**
     * Create a detached, initialised ScheduleconfigRecord
     */
    public ScheduleconfigRecord(String cif, Integer feeid, Long begindate, Integer autorepeat, Integer status, Long createdat, Long modifiedat) {
        super(Scheduleconfig.SCHEDULECONFIG);

        set(0, cif);
        set(1, feeid);
        set(2, begindate);
        set(3, autorepeat);
        set(4, status);
        set(5, createdat);
        set(6, modifiedat);
    }
}
