/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import mongoDB.model.tables.Services;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicesRecord extends UpdatableRecordImpl<ServicesRecord> implements Record12<Integer, String, String, String, String, String, String, Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2108708303;

    /**
     * Setter for <code>transaction.services.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.services.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transaction.services.titleVn</code>.
     */
    public void setTitlevn(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.services.titleVn</code>.
     */
    public String getTitlevn() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.services.titleEn</code>.
     */
    public void setTitleen(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.services.titleEn</code>.
     */
    public String getTitleen() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.services.icon</code>.
     */
    public void setIcon(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.services.icon</code>.
     */
    public String getIcon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transaction.services.image</code>.
     */
    public void setImage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.services.image</code>.
     */
    public String getImage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>transaction.services.descriptionVn</code>.
     */
    public void setDescriptionvn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.services.descriptionVn</code>.
     */
    public String getDescriptionvn() {
        return (String) get(5);
    }

    /**
     * Setter for <code>transaction.services.descriptionEn</code>.
     */
    public void setDescriptionen(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.services.descriptionEn</code>.
     */
    public String getDescriptionen() {
        return (String) get(6);
    }

    /**
     * Setter for <code>transaction.services.servicesType</code>.
     */
    public void setServicestype(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.services.servicesType</code>.
     */
    public Integer getServicestype() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>transaction.services.status</code>.
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.services.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>transaction.services.modifiedBy</code>.
     */
    public void setModifiedby(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>transaction.services.modifiedBy</code>.
     */
    public String getModifiedby() {
        return (String) get(9);
    }

    /**
     * Setter for <code>transaction.services.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>transaction.services.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>transaction.services.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>transaction.services.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, String, String, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, String, String, Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Services.SERVICES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Services.SERVICES.TITLEVN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Services.SERVICES.TITLEEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Services.SERVICES.ICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Services.SERVICES.IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Services.SERVICES.DESCRIPTIONVN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Services.SERVICES.DESCRIPTIONEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Services.SERVICES.SERVICESTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Services.SERVICES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Services.SERVICES.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Services.SERVICES.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Services.SERVICES.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitlevn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitleen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescriptionvn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescriptionen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getServicestype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value2(String value) {
        setTitlevn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value3(String value) {
        setTitleen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value4(String value) {
        setIcon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value5(String value) {
        setImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value6(String value) {
        setDescriptionvn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value7(String value) {
        setDescriptionen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value8(Integer value) {
        setServicestype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value10(String value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value11(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value12(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, Integer value9, String value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicesRecord
     */
    public ServicesRecord() {
        super(Services.SERVICES);
    }

    /**
     * Create a detached, initialised ServicesRecord
     */
    public ServicesRecord(Integer id, String titlevn, String titleen, String icon, String image, String descriptionvn, String descriptionen, Integer servicestype, Integer status, String modifiedby, Timestamp createdat, Timestamp modifiedat) {
        super(Services.SERVICES);

        set(0, id);
        set(1, titlevn);
        set(2, titleen);
        set(3, icon);
        set(4, image);
        set(5, descriptionvn);
        set(6, descriptionen);
        set(7, servicestype);
        set(8, status);
        set(9, modifiedby);
        set(10, createdat);
        set(11, modifiedat);
    }
}
