/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import mongoDB.model.tables.Transactionrule;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionruleRecord extends UpdatableRecordImpl<TransactionruleRecord> implements Record5<Integer, Integer, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1532544846;

    /**
     * Setter for <code>transaction.transactionRule.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.transactionRule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transaction.transactionRule.maxTimePerDay</code>.
     */
    public void setMaxtimeperday(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.transactionRule.maxTimePerDay</code>.
     */
    public Integer getMaxtimeperday() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>transaction.transactionRule.maxPerDay</code>.
     */
    public void setMaxperday(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.transactionRule.maxPerDay</code>.
     */
    public BigDecimal getMaxperday() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>transaction.transactionRule.maxPerTxn</code>.
     */
    public void setMaxpertxn(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.transactionRule.maxPerTxn</code>.
     */
    public BigDecimal getMaxpertxn() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>transaction.transactionRule.minPerTxn</code>.
     */
    public void setMinpertxn(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.transactionRule.minPerTxn</code>.
     */
    public BigDecimal getMinpertxn() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Transactionrule.TRANSACTIONRULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Transactionrule.TRANSACTIONRULE.MAXTIMEPERDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Transactionrule.TRANSACTIONRULE.MAXPERDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Transactionrule.TRANSACTIONRULE.MAXPERTXN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Transactionrule.TRANSACTIONRULE.MINPERTXN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMaxtimeperday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getMaxperday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getMaxpertxn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getMinpertxn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionruleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionruleRecord value2(Integer value) {
        setMaxtimeperday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionruleRecord value3(BigDecimal value) {
        setMaxperday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionruleRecord value4(BigDecimal value) {
        setMaxpertxn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionruleRecord value5(BigDecimal value) {
        setMinpertxn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionruleRecord values(Integer value1, Integer value2, BigDecimal value3, BigDecimal value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionruleRecord
     */
    public TransactionruleRecord() {
        super(Transactionrule.TRANSACTIONRULE);
    }

    /**
     * Create a detached, initialised TransactionruleRecord
     */
    public TransactionruleRecord(Integer id, Integer maxtimeperday, BigDecimal maxperday, BigDecimal maxpertxn, BigDecimal minpertxn) {
        super(Transactionrule.TRANSACTIONRULE);

        set(0, id);
        set(1, maxtimeperday);
        set(2, maxperday);
        set(3, maxpertxn);
        set(4, minpertxn);
    }
}
