/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import mongoDB.model.tables.Transactiontype;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactiontypeRecord extends UpdatableRecordImpl<TransactiontypeRecord> implements Record9<String, String, String, String, Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1978013799;

    /**
     * Setter for <code>transaction.transactionType.transactionType</code>.
     */
    public void setTransactiontype(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.transactionType.transactionType</code>.
     */
    public String getTransactiontype() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transaction.transactionType.nameType</code>.
     */
    public void setNametype(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.transactionType.nameType</code>.
     */
    public String getNametype() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.transactionType.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.transactionType.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.transactionType.currency</code>.
     */
    public void setCurrency(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.transactionType.currency</code>.
     */
    public String getCurrency() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transaction.transactionType.status</code>.
     */
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.transactionType.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>transaction.transactionType.ruleId</code>.
     */
    public void setRuleid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.transactionType.ruleId</code>.
     */
    public Integer getRuleid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>transaction.transactionType.administrators</code>.
     */
    public void setAdministrators(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.transactionType.administrators</code>.
     */
    public String getAdministrators() {
        return (String) get(6);
    }

    /**
     * Setter for <code>transaction.transactionType.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.transactionType.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>transaction.transactionType.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.transactionType.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Transactiontype.TRANSACTIONTYPE.TRANSACTIONTYPE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Transactiontype.TRANSACTIONTYPE.NAMETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Transactiontype.TRANSACTIONTYPE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Transactiontype.TRANSACTIONTYPE.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Transactiontype.TRANSACTIONTYPE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Transactiontype.TRANSACTIONTYPE.RULEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Transactiontype.TRANSACTIONTYPE.ADMINISTRATORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Transactiontype.TRANSACTIONTYPE.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Transactiontype.TRANSACTIONTYPE.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTransactiontype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNametype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getRuleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAdministrators();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value1(String value) {
        setTransactiontype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value2(String value) {
        setNametype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value4(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value6(Integer value) {
        setRuleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value7(String value) {
        setAdministrators(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value8(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord value9(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactiontypeRecord values(String value1, String value2, String value3, String value4, Integer value5, Integer value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactiontypeRecord
     */
    public TransactiontypeRecord() {
        super(Transactiontype.TRANSACTIONTYPE);
    }

    /**
     * Create a detached, initialised TransactiontypeRecord
     */
    public TransactiontypeRecord(String transactiontype, String nametype, String description, String currency, Integer status, Integer ruleid, String administrators, Timestamp createdat, Timestamp modifiedat) {
        super(Transactiontype.TRANSACTIONTYPE);

        set(0, transactiontype);
        set(1, nametype);
        set(2, description);
        set(3, currency);
        set(4, status);
        set(5, ruleid);
        set(6, administrators);
        set(7, createdat);
        set(8, modifiedat);
    }
}
