/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import mongoDB.model.tables.Transaction;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionRecord extends UpdatableRecordImpl<TransactionRecord> {

    private static final long serialVersionUID = 634913531;

    /**
     * Setter for <code>transaction.transaction.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.transaction.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transaction.transaction.transactionNumber</code>.
     */
    public void setTransactionnumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.transaction.transactionNumber</code>.
     */
    public String getTransactionnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.transaction.displayTransaction</code>.
     */
    public void setDisplaytransaction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.transaction.displayTransaction</code>.
     */
    public String getDisplaytransaction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.transaction.transactionType</code>.
     */
    public void setTransactiontype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.transaction.transactionType</code>.
     */
    public String getTransactiontype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transaction.transaction.refKey</code>.
     */
    public void setRefkey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.transaction.refKey</code>.
     */
    public String getRefkey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>transaction.transaction.createDate</code>.
     */
    public void setCreatedate(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.transaction.createDate</code>.
     */
    public Date getCreatedate() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>transaction.transaction.createTime</code>.
     */
    public void setCreatetime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.transaction.createTime</code>.
     */
    public Long getCreatetime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>transaction.transaction.status</code>.
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.transaction.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>transaction.transaction.prstatus</code>.
     */
    public void setPrstatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.transaction.prstatus</code>.
     */
    public Integer getPrstatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>transaction.transaction.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>transaction.transaction.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>transaction.transaction.typeDescription</code>.
     */
    public void setTypedescription(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>transaction.transaction.typeDescription</code>.
     */
    public Integer getTypedescription() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>transaction.transaction.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>transaction.transaction.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>transaction.transaction.feeAmount</code>.
     */
    public void setFeeamount(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>transaction.transaction.feeAmount</code>.
     */
    public BigDecimal getFeeamount() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>transaction.transaction.topupNumber</code>.
     */
    public void setTopupnumber(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>transaction.transaction.topupNumber</code>.
     */
    public String getTopupnumber() {
        return (String) get(13);
    }

    /**
     * Setter for <code>transaction.transaction.billNumber</code>.
     */
    public void setBillnumber(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>transaction.transaction.billNumber</code>.
     */
    public String getBillnumber() {
        return (String) get(14);
    }

    /**
     * Setter for <code>transaction.transaction.currency</code>.
     */
    public void setCurrency(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>transaction.transaction.currency</code>.
     */
    public String getCurrency() {
        return (String) get(15);
    }

    /**
     * Setter for <code>transaction.transaction.refSourceCIF</code>.
     */
    public void setRefsourcecif(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>transaction.transaction.refSourceCIF</code>.
     */
    public String getRefsourcecif() {
        return (String) get(16);
    }

    /**
     * Setter for <code>transaction.transaction.sourceCIF</code>.
     */
    public void setSourcecif(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>transaction.transaction.sourceCIF</code>.
     */
    public String getSourcecif() {
        return (String) get(17);
    }

    /**
     * Setter for <code>transaction.transaction.sourceName</code>.
     */
    public void setSourcename(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>transaction.transaction.sourceName</code>.
     */
    public String getSourcename() {
        return (String) get(18);
    }

    /**
     * Setter for <code>transaction.transaction.refSourceAccountNumber</code>.
     */
    public void setRefsourceaccountnumber(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>transaction.transaction.refSourceAccountNumber</code>.
     */
    public String getRefsourceaccountnumber() {
        return (String) get(19);
    }

    /**
     * Setter for <code>transaction.transaction.sourceAccountNumber</code>.
     */
    public void setSourceaccountnumber(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>transaction.transaction.sourceAccountNumber</code>.
     */
    public String getSourceaccountnumber() {
        return (String) get(20);
    }

    /**
     * Setter for <code>transaction.transaction.sourceCardNumber</code>.
     */
    public void setSourcecardnumber(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>transaction.transaction.sourceCardNumber</code>.
     */
    public String getSourcecardnumber() {
        return (String) get(21);
    }

    /**
     * Setter for <code>transaction.transaction.refDestinationCIF</code>.
     */
    public void setRefdestinationcif(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>transaction.transaction.refDestinationCIF</code>.
     */
    public String getRefdestinationcif() {
        return (String) get(22);
    }

    /**
     * Setter for <code>transaction.transaction.destinationCIF</code>.
     */
    public void setDestinationcif(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationCIF</code>.
     */
    public String getDestinationcif() {
        return (String) get(23);
    }

    /**
     * Setter for <code>transaction.transaction.destinationName</code>.
     */
    public void setDestinationname(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationName</code>.
     */
    public String getDestinationname() {
        return (String) get(24);
    }

    /**
     * Setter for <code>transaction.transaction.destinationInputName</code>.
     */
    public void setDestinationinputname(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationInputName</code>.
     */
    public String getDestinationinputname() {
        return (String) get(25);
    }

    /**
     * Setter for <code>transaction.transaction.refDestinationAccountNumber</code>.
     */
    public void setRefdestinationaccountnumber(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>transaction.transaction.refDestinationAccountNumber</code>.
     */
    public String getRefdestinationaccountnumber() {
        return (String) get(26);
    }

    /**
     * Setter for <code>transaction.transaction.displayDestinationAccountNumber</code>.
     */
    public void setDisplaydestinationaccountnumber(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>transaction.transaction.displayDestinationAccountNumber</code>.
     */
    public String getDisplaydestinationaccountnumber() {
        return (String) get(27);
    }

    /**
     * Setter for <code>transaction.transaction.destinationAccountNumber</code>.
     */
    public void setDestinationaccountnumber(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationAccountNumber</code>.
     */
    public String getDestinationaccountnumber() {
        return (String) get(28);
    }

    /**
     * Setter for <code>transaction.transaction.destinationCardNumber</code>.
     */
    public void setDestinationcardnumber(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationCardNumber</code>.
     */
    public String getDestinationcardnumber() {
        return (String) get(29);
    }

    /**
     * Setter for <code>transaction.transaction.destinationBranch</code>.
     */
    public void setDestinationbranch(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationBranch</code>.
     */
    public String getDestinationbranch() {
        return (String) get(30);
    }

    /**
     * Setter for <code>transaction.transaction.destinationBank</code>.
     */
    public void setDestinationbank(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationBank</code>.
     */
    public String getDestinationbank() {
        return (String) get(31);
    }

    /**
     * Setter for <code>transaction.transaction.destinationCity</code>.
     */
    public void setDestinationcity(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>transaction.transaction.destinationCity</code>.
     */
    public String getDestinationcity() {
        return (String) get(32);
    }

    /**
     * Setter for <code>transaction.transaction.refTransactionID</code>.
     */
    public void setReftransactionid(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>transaction.transaction.refTransactionID</code>.
     */
    public String getReftransactionid() {
        return (String) get(33);
    }

    /**
     * Setter for <code>transaction.transaction.response</code>.
     */
    public void setResponse(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>transaction.transaction.response</code>.
     */
    public String getResponse() {
        return (String) get(34);
    }

    /**
     * Setter for <code>transaction.transaction.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(35, value);
    }

    /**
     * Getter for <code>transaction.transaction.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(35);
    }

    /**
     * Setter for <code>transaction.transaction.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(36, value);
    }

    /**
     * Getter for <code>transaction.transaction.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(36);
    }

    /**
     * Setter for <code>transaction.transaction.preserve01</code>.
     */
    public void setPreserve01(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>transaction.transaction.preserve01</code>.
     */
    public String getPreserve01() {
        return (String) get(37);
    }

    /**
     * Setter for <code>transaction.transaction.preserve02</code>.
     */
    public void setPreserve02(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>transaction.transaction.preserve02</code>.
     */
    public String getPreserve02() {
        return (String) get(38);
    }

    /**
     * Setter for <code>transaction.transaction.preserve03</code>.
     */
    public void setPreserve03(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>transaction.transaction.preserve03</code>.
     */
    public String getPreserve03() {
        return (String) get(39);
    }

    /**
     * Setter for <code>transaction.transaction.collationID</code>.
     */
    public void setCollationid(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>transaction.transaction.collationID</code>.
     */
    public String getCollationid() {
        return (String) get(40);
    }

    /**
     * Setter for <code>transaction.transaction.collationGroup</code>.
     */
    public void setCollationgroup(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>transaction.transaction.collationGroup</code>.
     */
    public String getCollationgroup() {
        return (String) get(41);
    }

    /**
     * Setter for <code>transaction.transaction.transactionBillType</code>.
     */
    public void setTransactionbilltype(Integer value) {
        set(42, value);
    }

    /**
     * Getter for <code>transaction.transaction.transactionBillType</code>.
     */
    public Integer getTransactionbilltype() {
        return (Integer) get(42);
    }

    /**
     * Setter for <code>transaction.transaction.transferMoneyType</code>.
     */
    public void setTransfermoneytype(Integer value) {
        set(43, value);
    }

    /**
     * Getter for <code>transaction.transaction.transferMoneyType</code>.
     */
    public Integer getTransfermoneytype() {
        return (Integer) get(43);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionRecord
     */
    public TransactionRecord() {
        super(Transaction.TRANSACTION_);
    }

    /**
     * Create a detached, initialised TransactionRecord
     */
    public TransactionRecord(Integer id, String transactionnumber, String displaytransaction, String transactiontype, String refkey, Date createdate, Long createtime, Integer status, Integer prstatus, String description, Integer typedescription, BigDecimal amount, BigDecimal feeamount, String topupnumber, String billnumber, String currency, String refsourcecif, String sourcecif, String sourcename, String refsourceaccountnumber, String sourceaccountnumber, String sourcecardnumber, String refdestinationcif, String destinationcif, String destinationname, String destinationinputname, String refdestinationaccountnumber, String displaydestinationaccountnumber, String destinationaccountnumber, String destinationcardnumber, String destinationbranch, String destinationbank, String destinationcity, String reftransactionid, String response, Timestamp createdat, Timestamp modifiedat, String preserve01, String preserve02, String preserve03, String collationid, String collationgroup, Integer transactionbilltype, Integer transfermoneytype) {
        super(Transaction.TRANSACTION_);

        set(0, id);
        set(1, transactionnumber);
        set(2, displaytransaction);
        set(3, transactiontype);
        set(4, refkey);
        set(5, createdate);
        set(6, createtime);
        set(7, status);
        set(8, prstatus);
        set(9, description);
        set(10, typedescription);
        set(11, amount);
        set(12, feeamount);
        set(13, topupnumber);
        set(14, billnumber);
        set(15, currency);
        set(16, refsourcecif);
        set(17, sourcecif);
        set(18, sourcename);
        set(19, refsourceaccountnumber);
        set(20, sourceaccountnumber);
        set(21, sourcecardnumber);
        set(22, refdestinationcif);
        set(23, destinationcif);
        set(24, destinationname);
        set(25, destinationinputname);
        set(26, refdestinationaccountnumber);
        set(27, displaydestinationaccountnumber);
        set(28, destinationaccountnumber);
        set(29, destinationcardnumber);
        set(30, destinationbranch);
        set(31, destinationbank);
        set(32, destinationcity);
        set(33, reftransactionid);
        set(34, response);
        set(35, createdat);
        set(36, modifiedat);
        set(37, preserve01);
        set(38, preserve02);
        set(39, preserve03);
        set(40, collationid);
        set(41, collationgroup);
        set(42, transactionbilltype);
        set(43, transfermoneytype);
    }
}
