/*
 * This file is generated by jOOQ.
*/
package mongoDB.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import mongoDB.model.tables.Userloans;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserloansRecord extends UpdatableRecordImpl<UserloansRecord> implements Record19<Integer, String, String, Integer, Integer, Long, Integer, String, Double, String, String, Long, Integer, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -362311166;

    /**
     * Setter for <code>transaction.userLoans.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.userLoans.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transaction.userLoans.displayLoans</code>.
     */
    public void setDisplayloans(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.userLoans.displayLoans</code>.
     */
    public String getDisplayloans() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.userLoans.cif</code>.
     */
    public void setCif(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.userLoans.cif</code>.
     */
    public String getCif() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.userLoans.productId</code>.
     */
    public void setProductid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.userLoans.productId</code>.
     */
    public Integer getProductid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>transaction.userLoans.productTypeId</code>.
     */
    public void setProducttypeid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.userLoans.productTypeId</code>.
     */
    public Integer getProducttypeid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>transaction.userLoans.loans</code>.
     */
    public void setLoans(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.userLoans.loans</code>.
     */
    public Long getLoans() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>transaction.userLoans.period</code>.
     */
    public void setPeriod(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.userLoans.period</code>.
     */
    public Integer getPeriod() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>transaction.userLoans.currency</code>.
     */
    public void setCurrency(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.userLoans.currency</code>.
     */
    public String getCurrency() {
        return (String) get(7);
    }

    /**
     * Setter for <code>transaction.userLoans.inRate</code>.
     */
    public void setInrate(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.userLoans.inRate</code>.
     */
    public Double getInrate() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>transaction.userLoans.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>transaction.userLoans.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>transaction.userLoans.adminApprove</code>.
     */
    public void setAdminapprove(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>transaction.userLoans.adminApprove</code>.
     */
    public String getAdminapprove() {
        return (String) get(10);
    }

    /**
     * Setter for <code>transaction.userLoans.timeApprove</code>.
     */
    public void setTimeapprove(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>transaction.userLoans.timeApprove</code>.
     */
    public Long getTimeapprove() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>transaction.userLoans.status</code>.
     */
    public void setStatus(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>transaction.userLoans.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>transaction.userLoans.causeDenied</code>.
     */
    public void setCausedenied(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>transaction.userLoans.causeDenied</code>.
     */
    public String getCausedenied() {
        return (String) get(13);
    }

    /**
     * Setter for <code>transaction.userLoans.planPaying</code>.
     */
    public void setPlanpaying(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>transaction.userLoans.planPaying</code>.
     */
    public String getPlanpaying() {
        return (String) get(14);
    }

    /**
     * Setter for <code>transaction.userLoans.billID</code>.
     */
    public void setBillid(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>transaction.userLoans.billID</code>.
     */
    public String getBillid() {
        return (String) get(15);
    }

    /**
     * Setter for <code>transaction.userLoans.loanRefno</code>.
     */
    public void setLoanrefno(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>transaction.userLoans.loanRefno</code>.
     */
    public String getLoanrefno() {
        return (String) get(16);
    }

    /**
     * Setter for <code>transaction.userLoans.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>transaction.userLoans.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>transaction.userLoans.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>transaction.userLoans.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, String, Integer, Integer, Long, Integer, String, Double, String, String, Long, Integer, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, String, Integer, Integer, Long, Integer, String, Double, String, String, Long, Integer, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Userloans.USERLOANS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Userloans.USERLOANS.DISPLAYLOANS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Userloans.USERLOANS.CIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Userloans.USERLOANS.PRODUCTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Userloans.USERLOANS.PRODUCTTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Userloans.USERLOANS.LOANS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Userloans.USERLOANS.PERIOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Userloans.USERLOANS.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return Userloans.USERLOANS.INRATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Userloans.USERLOANS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Userloans.USERLOANS.ADMINAPPROVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Userloans.USERLOANS.TIMEAPPROVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Userloans.USERLOANS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Userloans.USERLOANS.CAUSEDENIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Userloans.USERLOANS.PLANPAYING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Userloans.USERLOANS.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Userloans.USERLOANS.LOANREFNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return Userloans.USERLOANS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field19() {
        return Userloans.USERLOANS.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDisplayloans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getProductid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getProducttypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getLoans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getInrate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAdminapprove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getTimeapprove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCausedenied();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getPlanpaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getLoanrefno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value19() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value2(String value) {
        setDisplayloans(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value3(String value) {
        setCif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value4(Integer value) {
        setProductid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value5(Integer value) {
        setProducttypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value6(Long value) {
        setLoans(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value7(Integer value) {
        setPeriod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value8(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value9(Double value) {
        setInrate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value10(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value11(String value) {
        setAdminapprove(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value12(Long value) {
        setTimeapprove(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value13(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value14(String value) {
        setCausedenied(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value15(String value) {
        setPlanpaying(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value16(String value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value17(String value) {
        setLoanrefno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value18(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord value19(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserloansRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Long value6, Integer value7, String value8, Double value9, String value10, String value11, Long value12, Integer value13, String value14, String value15, String value16, String value17, Timestamp value18, Timestamp value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserloansRecord
     */
    public UserloansRecord() {
        super(Userloans.USERLOANS);
    }

    /**
     * Create a detached, initialised UserloansRecord
     */
    public UserloansRecord(Integer id, String displayloans, String cif, Integer productid, Integer producttypeid, Long loans, Integer period, String currency, Double inrate, String description, String adminapprove, Long timeapprove, Integer status, String causedenied, String planpaying, String billid, String loanrefno, Timestamp createdat, Timestamp modifiedat) {
        super(Userloans.USERLOANS);

        set(0, id);
        set(1, displayloans);
        set(2, cif);
        set(3, productid);
        set(4, producttypeid);
        set(5, loans);
        set(6, period);
        set(7, currency);
        set(8, inrate);
        set(9, description);
        set(10, adminapprove);
        set(11, timeapprove);
        set(12, status);
        set(13, causedenied);
        set(14, planpaying);
        set(15, billid);
        set(16, loanrefno);
        set(17, createdat);
        set(18, modifiedat);
    }
}
