/*
 * This file is generated by jOOQ.
*/
package mongoDB.model;


import javax.annotation.Generated;

import mongoDB.model.tables.Bankbranch;
import mongoDB.model.tables.Bankcode;
import mongoDB.model.tables.Customertype;
import mongoDB.model.tables.Ddtransaction;
import mongoDB.model.tables.Fdaccount;
import mongoDB.model.tables.Fdtrans;
import mongoDB.model.tables.Fdtype;
import mongoDB.model.tables.Fee;
import mongoDB.model.tables.Loandescription;
import mongoDB.model.tables.Paymentschedule;
import mongoDB.model.tables.Products;
import mongoDB.model.tables.Producttype;
import mongoDB.model.tables.Scheduleconfig;
import mongoDB.model.tables.Services;
import mongoDB.model.tables.Timeline;
import mongoDB.model.tables.Transaction;
import mongoDB.model.tables.Transactionrule;
import mongoDB.model.tables.Transactiontype;
import mongoDB.model.tables.Transverify;
import mongoDB.model.tables.Updatepaymentschedule;
import mongoDB.model.tables.Userloans;
import mongoDB.model.tables.records.BankbranchRecord;
import mongoDB.model.tables.records.BankcodeRecord;
import mongoDB.model.tables.records.CustomertypeRecord;
import mongoDB.model.tables.records.DdtransactionRecord;
import mongoDB.model.tables.records.FdaccountRecord;
import mongoDB.model.tables.records.FdtransRecord;
import mongoDB.model.tables.records.FdtypeRecord;
import mongoDB.model.tables.records.FeeRecord;
import mongoDB.model.tables.records.LoandescriptionRecord;
import mongoDB.model.tables.records.PaymentscheduleRecord;
import mongoDB.model.tables.records.ProductsRecord;
import mongoDB.model.tables.records.ProducttypeRecord;
import mongoDB.model.tables.records.ScheduleconfigRecord;
import mongoDB.model.tables.records.ServicesRecord;
import mongoDB.model.tables.records.TimelineRecord;
import mongoDB.model.tables.records.TransactionRecord;
import mongoDB.model.tables.records.TransactionruleRecord;
import mongoDB.model.tables.records.TransactiontypeRecord;
import mongoDB.model.tables.records.TransverifyRecord;
import mongoDB.model.tables.records.UpdatepaymentscheduleRecord;
import mongoDB.model.tables.records.UserloansRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>transaction</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomertypeRecord, Integer> IDENTITY_CUSTOMERTYPE = Identities0.IDENTITY_CUSTOMERTYPE;
    public static final Identity<FeeRecord, Integer> IDENTITY_FEE = Identities0.IDENTITY_FEE;
    public static final Identity<LoandescriptionRecord, Integer> IDENTITY_LOANDESCRIPTION = Identities0.IDENTITY_LOANDESCRIPTION;
    public static final Identity<PaymentscheduleRecord, Integer> IDENTITY_PAYMENTSCHEDULE = Identities0.IDENTITY_PAYMENTSCHEDULE;
    public static final Identity<ProductsRecord, Integer> IDENTITY_PRODUCTS = Identities0.IDENTITY_PRODUCTS;
    public static final Identity<ProducttypeRecord, Integer> IDENTITY_PRODUCTTYPE = Identities0.IDENTITY_PRODUCTTYPE;
    public static final Identity<ServicesRecord, Integer> IDENTITY_SERVICES = Identities0.IDENTITY_SERVICES;
    public static final Identity<TimelineRecord, Integer> IDENTITY_TIMELINE = Identities0.IDENTITY_TIMELINE;
    public static final Identity<TransactionRecord, Integer> IDENTITY_TRANSACTION_ = Identities0.IDENTITY_TRANSACTION_;
    public static final Identity<TransactionruleRecord, Integer> IDENTITY_TRANSACTIONRULE = Identities0.IDENTITY_TRANSACTIONRULE;
    public static final Identity<UpdatepaymentscheduleRecord, Integer> IDENTITY_UPDATEPAYMENTSCHEDULE = Identities0.IDENTITY_UPDATEPAYMENTSCHEDULE;
    public static final Identity<UserloansRecord, Integer> IDENTITY_USERLOANS = Identities0.IDENTITY_USERLOANS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BankbranchRecord> KEY_BANKBRANCH_PRIMARY = UniqueKeys0.KEY_BANKBRANCH_PRIMARY;
    public static final UniqueKey<BankcodeRecord> KEY_BANKCODE_PRIMARY = UniqueKeys0.KEY_BANKCODE_PRIMARY;
    public static final UniqueKey<CustomertypeRecord> KEY_CUSTOMERTYPE_PRIMARY = UniqueKeys0.KEY_CUSTOMERTYPE_PRIMARY;
    public static final UniqueKey<DdtransactionRecord> KEY_DDTRANSACTION_PRIMARY = UniqueKeys0.KEY_DDTRANSACTION_PRIMARY;
    public static final UniqueKey<FdaccountRecord> KEY_FDACCOUNT_PRIMARY = UniqueKeys0.KEY_FDACCOUNT_PRIMARY;
    public static final UniqueKey<FdtransRecord> KEY_FDTRANS_PRIMARY = UniqueKeys0.KEY_FDTRANS_PRIMARY;
    public static final UniqueKey<FdtypeRecord> KEY_FDTYPE_PRIMARY = UniqueKeys0.KEY_FDTYPE_PRIMARY;
    public static final UniqueKey<FeeRecord> KEY_FEE_PRIMARY = UniqueKeys0.KEY_FEE_PRIMARY;
    public static final UniqueKey<LoandescriptionRecord> KEY_LOANDESCRIPTION_PRIMARY = UniqueKeys0.KEY_LOANDESCRIPTION_PRIMARY;
    public static final UniqueKey<PaymentscheduleRecord> KEY_PAYMENTSCHEDULE_PRIMARY = UniqueKeys0.KEY_PAYMENTSCHEDULE_PRIMARY;
    public static final UniqueKey<ProductsRecord> KEY_PRODUCTS_PRIMARY = UniqueKeys0.KEY_PRODUCTS_PRIMARY;
    public static final UniqueKey<ProducttypeRecord> KEY_PRODUCTTYPE_PRIMARY = UniqueKeys0.KEY_PRODUCTTYPE_PRIMARY;
    public static final UniqueKey<ScheduleconfigRecord> KEY_SCHEDULECONFIG_PRIMARY = UniqueKeys0.KEY_SCHEDULECONFIG_PRIMARY;
    public static final UniqueKey<ServicesRecord> KEY_SERVICES_PRIMARY = UniqueKeys0.KEY_SERVICES_PRIMARY;
    public static final UniqueKey<TimelineRecord> KEY_TIMELINE_PRIMARY = UniqueKeys0.KEY_TIMELINE_PRIMARY;
    public static final UniqueKey<TransactionRecord> KEY_TRANSACTION_ID = UniqueKeys0.KEY_TRANSACTION_ID;
    public static final UniqueKey<TransactionRecord> KEY_TRANSACTION_PRIMARY = UniqueKeys0.KEY_TRANSACTION_PRIMARY;
    public static final UniqueKey<TransactionruleRecord> KEY_TRANSACTIONRULE_PRIMARY = UniqueKeys0.KEY_TRANSACTIONRULE_PRIMARY;
    public static final UniqueKey<TransactiontypeRecord> KEY_TRANSACTIONTYPE_PRIMARY = UniqueKeys0.KEY_TRANSACTIONTYPE_PRIMARY;
    public static final UniqueKey<TransverifyRecord> KEY_TRANSVERIFY_PRIMARY = UniqueKeys0.KEY_TRANSVERIFY_PRIMARY;
    public static final UniqueKey<UpdatepaymentscheduleRecord> KEY_UPDATEPAYMENTSCHEDULE_PRIMARY = UniqueKeys0.KEY_UPDATEPAYMENTSCHEDULE_PRIMARY;
    public static final UniqueKey<UserloansRecord> KEY_USERLOANS_PRIMARY = UniqueKeys0.KEY_USERLOANS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CustomertypeRecord, Integer> IDENTITY_CUSTOMERTYPE = createIdentity(Customertype.CUSTOMERTYPE, Customertype.CUSTOMERTYPE.ID);
        public static Identity<FeeRecord, Integer> IDENTITY_FEE = createIdentity(Fee.FEE, Fee.FEE.FEEID);
        public static Identity<LoandescriptionRecord, Integer> IDENTITY_LOANDESCRIPTION = createIdentity(Loandescription.LOANDESCRIPTION, Loandescription.LOANDESCRIPTION.ID);
        public static Identity<PaymentscheduleRecord, Integer> IDENTITY_PAYMENTSCHEDULE = createIdentity(Paymentschedule.PAYMENTSCHEDULE, Paymentschedule.PAYMENTSCHEDULE.ID);
        public static Identity<ProductsRecord, Integer> IDENTITY_PRODUCTS = createIdentity(Products.PRODUCTS, Products.PRODUCTS.ID);
        public static Identity<ProducttypeRecord, Integer> IDENTITY_PRODUCTTYPE = createIdentity(Producttype.PRODUCTTYPE, Producttype.PRODUCTTYPE.PRODUCTTYPEID);
        public static Identity<ServicesRecord, Integer> IDENTITY_SERVICES = createIdentity(Services.SERVICES, Services.SERVICES.ID);
        public static Identity<TimelineRecord, Integer> IDENTITY_TIMELINE = createIdentity(Timeline.TIMELINE, Timeline.TIMELINE.ID);
        public static Identity<TransactionRecord, Integer> IDENTITY_TRANSACTION_ = createIdentity(Transaction.TRANSACTION_, Transaction.TRANSACTION_.ID);
        public static Identity<TransactionruleRecord, Integer> IDENTITY_TRANSACTIONRULE = createIdentity(Transactionrule.TRANSACTIONRULE, Transactionrule.TRANSACTIONRULE.ID);
        public static Identity<UpdatepaymentscheduleRecord, Integer> IDENTITY_UPDATEPAYMENTSCHEDULE = createIdentity(Updatepaymentschedule.UPDATEPAYMENTSCHEDULE, Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.ID);
        public static Identity<UserloansRecord, Integer> IDENTITY_USERLOANS = createIdentity(Userloans.USERLOANS, Userloans.USERLOANS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BankbranchRecord> KEY_BANKBRANCH_PRIMARY = createUniqueKey(Bankbranch.BANKBRANCH, "KEY_bankBranch_PRIMARY", Bankbranch.BANKBRANCH.BRANCHID);
        public static final UniqueKey<BankcodeRecord> KEY_BANKCODE_PRIMARY = createUniqueKey(Bankcode.BANKCODE, "KEY_bankCode_PRIMARY", Bankcode.BANKCODE.BANKCODE_);
        public static final UniqueKey<CustomertypeRecord> KEY_CUSTOMERTYPE_PRIMARY = createUniqueKey(Customertype.CUSTOMERTYPE, "KEY_customerType_PRIMARY", Customertype.CUSTOMERTYPE.ID);
        public static final UniqueKey<DdtransactionRecord> KEY_DDTRANSACTION_PRIMARY = createUniqueKey(Ddtransaction.DDTRANSACTION, "KEY_ddTransaction_PRIMARY", Ddtransaction.DDTRANSACTION.TRANSACTIONNUMBER, Ddtransaction.DDTRANSACTION.ACCOUNTNUMBER);
        public static final UniqueKey<FdaccountRecord> KEY_FDACCOUNT_PRIMARY = createUniqueKey(Fdaccount.FDACCOUNT, "KEY_fdAccount_PRIMARY", Fdaccount.FDACCOUNT.FDACCOUNTNUMBER);
        public static final UniqueKey<FdtransRecord> KEY_FDTRANS_PRIMARY = createUniqueKey(Fdtrans.FDTRANS, "KEY_fdTrans_PRIMARY", Fdtrans.FDTRANS.FDTRANSID);
        public static final UniqueKey<FdtypeRecord> KEY_FDTYPE_PRIMARY = createUniqueKey(Fdtype.FDTYPE, "KEY_fdType_PRIMARY", Fdtype.FDTYPE.FDTYPEID);
        public static final UniqueKey<FeeRecord> KEY_FEE_PRIMARY = createUniqueKey(Fee.FEE, "KEY_fee_PRIMARY", Fee.FEE.FEEID);
        public static final UniqueKey<LoandescriptionRecord> KEY_LOANDESCRIPTION_PRIMARY = createUniqueKey(Loandescription.LOANDESCRIPTION, "KEY_loanDescription_PRIMARY", Loandescription.LOANDESCRIPTION.ID);
        public static final UniqueKey<PaymentscheduleRecord> KEY_PAYMENTSCHEDULE_PRIMARY = createUniqueKey(Paymentschedule.PAYMENTSCHEDULE, "KEY_paymentSchedule_PRIMARY", Paymentschedule.PAYMENTSCHEDULE.ID);
        public static final UniqueKey<ProductsRecord> KEY_PRODUCTS_PRIMARY = createUniqueKey(Products.PRODUCTS, "KEY_products_PRIMARY", Products.PRODUCTS.ID);
        public static final UniqueKey<ProducttypeRecord> KEY_PRODUCTTYPE_PRIMARY = createUniqueKey(Producttype.PRODUCTTYPE, "KEY_productType_PRIMARY", Producttype.PRODUCTTYPE.PRODUCTTYPEID);
        public static final UniqueKey<ScheduleconfigRecord> KEY_SCHEDULECONFIG_PRIMARY = createUniqueKey(Scheduleconfig.SCHEDULECONFIG, "KEY_scheduleConfig_PRIMARY", Scheduleconfig.SCHEDULECONFIG.CIF);
        public static final UniqueKey<ServicesRecord> KEY_SERVICES_PRIMARY = createUniqueKey(Services.SERVICES, "KEY_services_PRIMARY", Services.SERVICES.ID);
        public static final UniqueKey<TimelineRecord> KEY_TIMELINE_PRIMARY = createUniqueKey(Timeline.TIMELINE, "KEY_timeLine_PRIMARY", Timeline.TIMELINE.ID);
        public static final UniqueKey<TransactionRecord> KEY_TRANSACTION_ID = createUniqueKey(Transaction.TRANSACTION_, "KEY_transaction_id", Transaction.TRANSACTION_.ID);
        public static final UniqueKey<TransactionRecord> KEY_TRANSACTION_PRIMARY = createUniqueKey(Transaction.TRANSACTION_, "KEY_transaction_PRIMARY", Transaction.TRANSACTION_.TRANSACTIONNUMBER);
        public static final UniqueKey<TransactionruleRecord> KEY_TRANSACTIONRULE_PRIMARY = createUniqueKey(Transactionrule.TRANSACTIONRULE, "KEY_transactionRule_PRIMARY", Transactionrule.TRANSACTIONRULE.ID);
        public static final UniqueKey<TransactiontypeRecord> KEY_TRANSACTIONTYPE_PRIMARY = createUniqueKey(Transactiontype.TRANSACTIONTYPE, "KEY_transactionType_PRIMARY", Transactiontype.TRANSACTIONTYPE.TRANSACTIONTYPE_);
        public static final UniqueKey<TransverifyRecord> KEY_TRANSVERIFY_PRIMARY = createUniqueKey(Transverify.TRANSVERIFY, "KEY_transVerify_PRIMARY", Transverify.TRANSVERIFY.TRANSACTIONNUMBER);
        public static final UniqueKey<UpdatepaymentscheduleRecord> KEY_UPDATEPAYMENTSCHEDULE_PRIMARY = createUniqueKey(Updatepaymentschedule.UPDATEPAYMENTSCHEDULE, "KEY_updatePaymentSchedule_PRIMARY", Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.ID);
        public static final UniqueKey<UserloansRecord> KEY_USERLOANS_PRIMARY = createUniqueKey(Userloans.USERLOANS, "KEY_userLoans_PRIMARY", Userloans.USERLOANS.ID);
    }
}
