/*
 * This file is generated by jOOQ.
*/
package mongoDB.model;


import javax.annotation.Generated;

import mongoDB.model.tables.Bankbranch;
import mongoDB.model.tables.Bankcode;
import mongoDB.model.tables.Citycode;
import mongoDB.model.tables.Customertype;
import mongoDB.model.tables.Ddtransaction;
import mongoDB.model.tables.Fdaccount;
import mongoDB.model.tables.Fdrate;
import mongoDB.model.tables.Fdtrans;
import mongoDB.model.tables.Fdtype;
import mongoDB.model.tables.Fee;
import mongoDB.model.tables.Loandescription;
import mongoDB.model.tables.Paymentschedule;
import mongoDB.model.tables.Products;
import mongoDB.model.tables.Producttype;
import mongoDB.model.tables.Scheduleconfig;
import mongoDB.model.tables.Services;
import mongoDB.model.tables.Timeline;
import mongoDB.model.tables.Transaction;
import mongoDB.model.tables.Transactionrule;
import mongoDB.model.tables.Transactiontype;
import mongoDB.model.tables.Transverify;
import mongoDB.model.tables.Updatepaymentschedule;
import mongoDB.model.tables.Userloans;


/**
 * Convenience access to all tables in transaction
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>transaction.bankBranch</code>.
     */
    public static final Bankbranch BANKBRANCH = mongoDB.model.tables.Bankbranch.BANKBRANCH;

    /**
     * The table <code>transaction.bankCode</code>.
     */
    public static final Bankcode BANKCODE = mongoDB.model.tables.Bankcode.BANKCODE;

    /**
     * The table <code>transaction.cityCode</code>.
     */
    public static final Citycode CITYCODE = mongoDB.model.tables.Citycode.CITYCODE;

    /**
     * The table <code>transaction.customerType</code>.
     */
    public static final Customertype CUSTOMERTYPE = mongoDB.model.tables.Customertype.CUSTOMERTYPE;

    /**
     * The table <code>transaction.ddTransaction</code>.
     */
    public static final Ddtransaction DDTRANSACTION = mongoDB.model.tables.Ddtransaction.DDTRANSACTION;

    /**
     * The table <code>transaction.fdAccount</code>.
     */
    public static final Fdaccount FDACCOUNT = mongoDB.model.tables.Fdaccount.FDACCOUNT;

    /**
     * The table <code>transaction.fdRate</code>.
     */
    public static final Fdrate FDRATE = mongoDB.model.tables.Fdrate.FDRATE;

    /**
     * The table <code>transaction.fdTrans</code>.
     */
    public static final Fdtrans FDTRANS = mongoDB.model.tables.Fdtrans.FDTRANS;

    /**
     * The table <code>transaction.fdType</code>.
     */
    public static final Fdtype FDTYPE = mongoDB.model.tables.Fdtype.FDTYPE;

    /**
     * The table <code>transaction.fee</code>.
     */
    public static final Fee FEE = mongoDB.model.tables.Fee.FEE;

    /**
     * The table <code>transaction.loanDescription</code>.
     */
    public static final Loandescription LOANDESCRIPTION = mongoDB.model.tables.Loandescription.LOANDESCRIPTION;

    /**
     * The table <code>transaction.paymentSchedule</code>.
     */
    public static final Paymentschedule PAYMENTSCHEDULE = mongoDB.model.tables.Paymentschedule.PAYMENTSCHEDULE;

    /**
     * The table <code>transaction.products</code>.
     */
    public static final Products PRODUCTS = mongoDB.model.tables.Products.PRODUCTS;

    /**
     * The table <code>transaction.productType</code>.
     */
    public static final Producttype PRODUCTTYPE = mongoDB.model.tables.Producttype.PRODUCTTYPE;

    /**
     * The table <code>transaction.scheduleConfig</code>.
     */
    public static final Scheduleconfig SCHEDULECONFIG = mongoDB.model.tables.Scheduleconfig.SCHEDULECONFIG;

    /**
     * The table <code>transaction.services</code>.
     */
    public static final Services SERVICES = mongoDB.model.tables.Services.SERVICES;

    /**
     * The table <code>transaction.timeLine</code>.
     */
    public static final Timeline TIMELINE = mongoDB.model.tables.Timeline.TIMELINE;

    /**
     * The table <code>transaction.transaction</code>.
     */
    public static final Transaction TRANSACTION_ = mongoDB.model.tables.Transaction.TRANSACTION_;

    /**
     * The table <code>transaction.transactionRule</code>.
     */
    public static final Transactionrule TRANSACTIONRULE = mongoDB.model.tables.Transactionrule.TRANSACTIONRULE;

    /**
     * The table <code>transaction.transactionType</code>.
     */
    public static final Transactiontype TRANSACTIONTYPE = mongoDB.model.tables.Transactiontype.TRANSACTIONTYPE;

    /**
     * The table <code>transaction.transVerify</code>.
     */
    public static final Transverify TRANSVERIFY = mongoDB.model.tables.Transverify.TRANSVERIFY;

    /**
     * The table <code>transaction.updatePaymentSchedule</code>.
     */
    public static final Updatepaymentschedule UPDATEPAYMENTSCHEDULE = mongoDB.model.tables.Updatepaymentschedule.UPDATEPAYMENTSCHEDULE;

    /**
     * The table <code>transaction.userLoans</code>.
     */
    public static final Userloans USERLOANS = mongoDB.model.tables.Userloans.USERLOANS;
}
