/*
 * This file is generated by jOOQ.
*/
package mongoDB.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mongoDB.model.tables.Bankbranch;
import mongoDB.model.tables.Bankcode;
import mongoDB.model.tables.Citycode;
import mongoDB.model.tables.Customertype;
import mongoDB.model.tables.Ddtransaction;
import mongoDB.model.tables.Fdaccount;
import mongoDB.model.tables.Fdrate;
import mongoDB.model.tables.Fdtrans;
import mongoDB.model.tables.Fdtype;
import mongoDB.model.tables.Fee;
import mongoDB.model.tables.Loandescription;
import mongoDB.model.tables.Paymentschedule;
import mongoDB.model.tables.Products;
import mongoDB.model.tables.Producttype;
import mongoDB.model.tables.Scheduleconfig;
import mongoDB.model.tables.Services;
import mongoDB.model.tables.Timeline;
import mongoDB.model.tables.Transactionrule;
import mongoDB.model.tables.Transactiontype;
import mongoDB.model.tables.Transverify;
import mongoDB.model.tables.Updatepaymentschedule;
import mongoDB.model.tables.Userloans;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction extends SchemaImpl {

    private static final long serialVersionUID = 1415820625;

    /**
     * The reference instance of <code>transaction</code>
     */
    public static final Transaction TRANSACTION = new Transaction();

    /**
     * The table <code>transaction.bankBranch</code>.
     */
    public final Bankbranch BANKBRANCH = mongoDB.model.tables.Bankbranch.BANKBRANCH;

    /**
     * The table <code>transaction.bankCode</code>.
     */
    public final Bankcode BANKCODE = mongoDB.model.tables.Bankcode.BANKCODE;

    /**
     * The table <code>transaction.cityCode</code>.
     */
    public final Citycode CITYCODE = mongoDB.model.tables.Citycode.CITYCODE;

    /**
     * The table <code>transaction.customerType</code>.
     */
    public final Customertype CUSTOMERTYPE = mongoDB.model.tables.Customertype.CUSTOMERTYPE;

    /**
     * The table <code>transaction.ddTransaction</code>.
     */
    public final Ddtransaction DDTRANSACTION = mongoDB.model.tables.Ddtransaction.DDTRANSACTION;

    /**
     * The table <code>transaction.fdAccount</code>.
     */
    public final Fdaccount FDACCOUNT = mongoDB.model.tables.Fdaccount.FDACCOUNT;

    /**
     * The table <code>transaction.fdRate</code>.
     */
    public final Fdrate FDRATE = mongoDB.model.tables.Fdrate.FDRATE;

    /**
     * The table <code>transaction.fdTrans</code>.
     */
    public final Fdtrans FDTRANS = mongoDB.model.tables.Fdtrans.FDTRANS;

    /**
     * The table <code>transaction.fdType</code>.
     */
    public final Fdtype FDTYPE = mongoDB.model.tables.Fdtype.FDTYPE;

    /**
     * The table <code>transaction.fee</code>.
     */
    public final Fee FEE = mongoDB.model.tables.Fee.FEE;

    /**
     * The table <code>transaction.loanDescription</code>.
     */
    public final Loandescription LOANDESCRIPTION = mongoDB.model.tables.Loandescription.LOANDESCRIPTION;

    /**
     * The table <code>transaction.paymentSchedule</code>.
     */
    public final Paymentschedule PAYMENTSCHEDULE = mongoDB.model.tables.Paymentschedule.PAYMENTSCHEDULE;

    /**
     * The table <code>transaction.products</code>.
     */
    public final Products PRODUCTS = mongoDB.model.tables.Products.PRODUCTS;

    /**
     * The table <code>transaction.productType</code>.
     */
    public final Producttype PRODUCTTYPE = mongoDB.model.tables.Producttype.PRODUCTTYPE;

    /**
     * The table <code>transaction.scheduleConfig</code>.
     */
    public final Scheduleconfig SCHEDULECONFIG = mongoDB.model.tables.Scheduleconfig.SCHEDULECONFIG;

    /**
     * The table <code>transaction.services</code>.
     */
    public final Services SERVICES = mongoDB.model.tables.Services.SERVICES;

    /**
     * The table <code>transaction.timeLine</code>.
     */
    public final Timeline TIMELINE = mongoDB.model.tables.Timeline.TIMELINE;

    /**
     * The table <code>transaction.transaction</code>.
     */
    public final mongoDB.model.tables.Transaction TRANSACTION_ = mongoDB.model.tables.Transaction.TRANSACTION_;

    /**
     * The table <code>transaction.transactionRule</code>.
     */
    public final Transactionrule TRANSACTIONRULE = mongoDB.model.tables.Transactionrule.TRANSACTIONRULE;

    /**
     * The table <code>transaction.transactionType</code>.
     */
    public final Transactiontype TRANSACTIONTYPE = mongoDB.model.tables.Transactiontype.TRANSACTIONTYPE;

    /**
     * The table <code>transaction.transVerify</code>.
     */
    public final Transverify TRANSVERIFY = mongoDB.model.tables.Transverify.TRANSVERIFY;

    /**
     * The table <code>transaction.updatePaymentSchedule</code>.
     */
    public final Updatepaymentschedule UPDATEPAYMENTSCHEDULE = mongoDB.model.tables.Updatepaymentschedule.UPDATEPAYMENTSCHEDULE;

    /**
     * The table <code>transaction.userLoans</code>.
     */
    public final Userloans USERLOANS = mongoDB.model.tables.Userloans.USERLOANS;

    /**
     * No further instances allowed
     */
    private Transaction() {
        super("transaction", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Bankbranch.BANKBRANCH,
            Bankcode.BANKCODE,
            Citycode.CITYCODE,
            Customertype.CUSTOMERTYPE,
            Ddtransaction.DDTRANSACTION,
            Fdaccount.FDACCOUNT,
            Fdrate.FDRATE,
            Fdtrans.FDTRANS,
            Fdtype.FDTYPE,
            Fee.FEE,
            Loandescription.LOANDESCRIPTION,
            Paymentschedule.PAYMENTSCHEDULE,
            Products.PRODUCTS,
            Producttype.PRODUCTTYPE,
            Scheduleconfig.SCHEDULECONFIG,
            Services.SERVICES,
            Timeline.TIMELINE,
            mongoDB.model.tables.Transaction.TRANSACTION_,
            Transactionrule.TRANSACTIONRULE,
            Transactiontype.TRANSACTIONTYPE,
            Transverify.TRANSVERIFY,
            Updatepaymentschedule.UPDATEPAYMENTSCHEDULE,
            Userloans.USERLOANS);
    }
}
